### ISSUE TITLE
Installation issue on mac.

### ISSUE THREAD

**Issue by SteveDiamond** [cvxgrp/scs#183]
**Please read this first**

If you are have a problem that SCS struggles with you can pass a string to the
`write_data_filename` argument and SCS will dump a file containing the problem
to disk. Zip the file and send it to us or attach it to this bug report for easy
reproduction of the issue.

A common cause of issues is not linking BLAS/LAPACK libraries correctly. If you
are having this issue please search for resources on installing and linking
these libraries first. You can try openblas if you need a BLAS library.

## Specifications
- OS: Mac, latest OS
- SCS Version: 2.1.4
- Compiler:

## Description
Someone with a vanilla Python 3 setup tried to install SCS and got an import error.

## How to reproduce
The problem occurred on two different machines with vanilla (no conda or venv) Python 3 setups.

## Output
```
>>> import cvxpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cvxpy/__init__.py", line 27, in <module>
    from cvxpy.problems.problem import Problem
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 35, in <module>
    from cvxpy.reductions import InverseData
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cvxpy/reductions/__init__.py", line 32, in <module>
    from cvxpy.reductions.solvers.solving_chain import SolvingChain
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cvxpy/reductions/solvers/solving_chain.py", line 21, in <module>
    from cvxpy.reductions.solvers import defines as slv_def
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cvxpy/reductions/solvers/defines.py", line 98, in <module>
    INSTALLED_SOLVERS = installed_solvers()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cvxpy/reductions/solvers/defines.py", line 87, in installed_solvers
    if solver.is_installed():
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cvxpy/reductions/solvers/solver.py", line 59, in is_installed
    self.import_solver()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cvxpy/reductions/solvers/conic_solvers/scs_conif.py", line 134, in import_solver
    import scs
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scs/__init__.py", line 5, in <module>
    import _scs_direct
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_scs_direct.cpython-38-darwin.so, 2): Library not loaded: @rpath/libmkl_rt.1.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_scs_direct.cpython-38-darwin.so
  Reason: image not found
```

**Comment by h-vetinari** [comment]
Sounds like the installation assumes presence of MKL, but doesn't find it at runtime:
```
Library not loaded: @rpath/libmkl_rt.1.dylib
```

Also, this issue might belong on the tracker of the python-interface: https://github.com/bodono/scs-python

**Comment by SteveDiamond** [comment]
Linked https://github.com/bodono/scs-python/issues/55

**Comment by bodono** [comment]
Closing in favor of the other issue.
