### ISSUE TITLE
cannot be deployed by pyinstaller

### ISSUE THREAD

**Issue by ShannonZ** [cvxgrp/scs#226]
## Specifications
- OS: Windows10 
- SCS Version:3.2.0
- Compiler: unknown, installed from pip

## Description
After deploy the official demo:
https://www.cvxgrp.org/scs/examples/python/basic_qp.html
using pyinstaller:
`pyinstalller -F basic_qp.py`
I can get a standalone exe file. But the exe cannot launch correctly.
The following exception was thrown:
`Traceback (most recent call last):
  File "scsdemo.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "scs\__init__.py", line 29, in <module>
  File "scs\__init__.py", line 23, in _delvewheel_init_patch_0_0_20
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\admin\\AppData\\Local\\Temp\\_MEI129002\\.load-order-scs-3.2.0'
[14508] Failed to execute script 'scsdemo' due to unhandled exception!`

## How to reproduce
`pyinstalller -F basic_qp.py` then double click the exe

I've tried `py2exe ` too, but encountered the same problem.
## Output
cannot run

**Comment by ShannonZ** [comment]
It seems that `os.join` after deployed changes to `os.os.join`. As a result, the location of lapack and blas would missing when run the exe. I've solved this issue temporarily by change this part of the code in __init__.py. Maybe a bug of pyinstaller.

**Comment by bodono** [comment]
Ok interesting, thanks for the update.
