### ISSUE TITLE
Python setup throws TypeError: dist must be a Distribution instance

### ISSUE THREAD

**Issue by anqif** [cvxgrp/scs#70]
I recently did a fresh git clone of scs in a virtual environment and tried to python setup.py install --scs, but received the following error:

Namespace(blas64=False, extraverbose=False, float32=False, gpu=False, int32=False, root_dir='../', scs=True)
Traceback (most recent call last):
  File "setup.py", line 239, in <module>
    run_install()
  File "setup.py", line 57, in run_install
    blas_info = get_info('blas_opt')
  File "/usr/local/lib/python2.7/dist-packages/numpy/distutils/system_info.py", line 372, in get_info
    return cl().get_info(notfound_action)
  File "/usr/local/lib/python2.7/dist-packages/numpy/distutils/system_info.py", line 560, in get_info
    self.calc_info()
  File "/usr/local/lib/python2.7/dist-packages/numpy/distutils/system_info.py", line 1598, in calc_info
    atlas_info = get_info('atlas_blas')
  File "/usr/local/lib/python2.7/dist-packages/numpy/distutils/system_info.py", line 372, in get_info
    return cl().get_info(notfound_action)
  File "/usr/local/lib/python2.7/dist-packages/numpy/distutils/system_info.py", line 560, in get_info
    self.calc_info()
  File "/usr/local/lib/python2.7/dist-packages/numpy/distutils/system_info.py", line 1176, in calc_info
    atlas_version, atlas_extra_info = get_atlas_version(**atlas)
  File "/usr/local/lib/python2.7/dist-packages/numpy/distutils/system_info.py", line 1409, in get_atlas_version
    c = cmd_config(Distribution())
  File "/usr/lib/python2.7/distutils/cmd.py", line 59, in __init__
    raise TypeError, "dist must be a Distribution instance"
TypeError: dist must be a Distribution instance

**Comment by bodono** [comment]
Maybe this thread on stackoverflow will shed some light:

http://stackoverflow.com/questions/21136266/typeerror-dist-must-be-a-distribution-instance-when-resolving-beautifulsoup-d

Try upgrading setuptools as the thread suggests.

**Comment by anqif** [comment]
I tried reinstalling setuptools-25.1.1-py2.py3-none-any.whl and got the same error. Also tried installing dnspython, and it made no difference.

**Comment by bodono** [comment]
Hmm, that's very strange. It's failiing in the get_info() call, which is a numpy method. Do you get the same error if you run the following commands in a fresh interpreter:
```python
from numpy.distutils.system_info import get_info
blas_info = get_info('blas_opt')
```

**Comment by anqif** [comment]
No errors with that code. Here's the Python output:

`>>> from numpy.distutils.system_info import get_info
>>> blas_info = get_info('blas_opt')
>>> blas_info
{'libraries': ['f77blas', 'cblas', 'atlas', 'f77blas', 'cblas'], 'library_dirs': ['/usr/lib/atlas-base'], 'define_macros': [('HAVE_CBLAS', None), ('NO_ATLAS_INFO', -1)], 'language': 'c', 'include_dirs': ['/usr/include/atlas']}`

**Comment by bodono** [comment]
What operating system are you using? Are you able to install just using `sudo pip install scs`?

**Comment by anqif** [comment]
Ubuntu 15.10. Yes,  installing scs with pip works, but I need it with GPU-support enabled.

**Comment by bodono** [comment]
You can install scs with GPU support via pip using:

```
sudo pip install scs --install-option="--scs" --install-option="--gpu"
```

**Comment by tachim** [comment]
I'm also seeing this same issue with `TypeError: dist must be a Distribution instance`

**Comment by HusterRC** [comment]
> I'm also seeing this same issue with `TypeError: dist must be a Distribution instance`

**Comment by bodono** [comment]
I don't think this has anything to do with SCS, see this thread: http://stackoverflow.com/questions/21136266/typeerror-dist-must-be-a-distribution-instance-when-resolving-beautifulsoup-d

**Comment by marziyemahmoudifar** [comment]
I also encountered this error when executing the bash make.sh command, can anyone help?
running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
cythoning pycocotools/_mask.pyx to pycocotools/_mask.c
error: /content/RGBD_fruit_detection_faster-rcnn.pytorch/lib/pycocotools/_mask.pyx
Compiling nms kernels by nvcc...
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
/content/RGBD_fruit_detection_faster-rcnn.pytorch/lib/model/nms
['/content/RGBD_fruit_detection_faster-rcnn.pytorch/lib/model/nms/src/nms_cuda_kernel.cu.o']
Traceback (most recent call last):
  File "build.py", line 32, in <module>
    extra_objects=extra_objects
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 233, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 172, in __init__
    _Command.__init__(self, dist)
  File "/usr/lib/python3.7/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
aveam si ha anat bé
Compiling roi pooling kernels by nvcc...
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
/content/RGBD_fruit_detection_faster-rcnn.pytorch/lib/model/roi_pooling
Traceback (most recent call last):
  File "build.py", line 32, in <module>
    extra_objects=extra_objects
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 233, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 172, in __init__
    _Command.__init__(self, dist)
  File "/usr/lib/python3.7/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
Compiling roi align kernels by nvcc...
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
/content/RGBD_fruit_detection_faster-rcnn.pytorch/lib/model/roi_align
Traceback (most recent call last):
  File "build.py", line 32, in <module>
    extra_objects=extra_objects
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 233, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 172, in __init__
    _Command.__init__(self, dist)
  File "/usr/lib/python3.7/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
Compiling roi crop kernels by nvcc...
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
/content/RGBD_fruit_detection_faster-rcnn.pytorch/lib/model/roi_crop
Traceback (most recent call last):
  File "build.py", line 31, in <module>
    extra_objects=extra_objects
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 233, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 172, in __init__
    _Command.__init__(self, dist)
  File "/usr/lib/python3.7/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
