### ISSUE TITLE
Use of uninitialized value

### ISSUE THREAD

**Issue by ccrusius** [cvxgrp/scs#89]
From running a program with `msan` enabled:

```
==733583==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f2ef2cba726 in accelerate scs/src/accel.c:206:7
    #1 0x7f2ef2cc89c8 in scs_solve scs/src/scs.c:893:9
    #2 0x7f2ef2cd0a96 in scs scs/src/scs.c:994:5
    ...

Uninitialized value was created by an allocation of 'info' in the stack frame of function 'solve_with_gesv'
    #0 0x7f2ef2cbadd0 in solve_with_gesv third_party/scs/src/accel.c:159

SUMMARY: MemorySanitizer: use-of-uninitialized-value third_party/scs/src/accel.c:206:7 in accelerate
Exiting
```

**Comment by bodono** [comment]
Thanks Cesar, should be fixed now.
